"use client";

import Link from "next/link";
import { useState } from "react";
import type { ReactNode, SVGProps } from "react";
import TwoFactorSettings from "./TwoFactorSettings";

export type OperationsPageKind = "cleaning"|"standardization"|"match-merge"|"validation"|"approval-queue"|"reports"|"audit-log"|"settings";
type IconProps = SVGProps<SVGSVGElement>;
function Icon({children,...props}:IconProps&{children:ReactNode}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}>{children}</svg>}

const icons={
 dashboard:<Icon><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></Icon>,
 upload:<Icon><path d="M12 16V4m0 0L7.5 8.5M12 4l4.5 4.5"/><path d="M5 14v5a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-5"/></Icon>,
 database:<Icon><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v7c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 12v7c0 1.7 3.6 3 8 3s8-1.3 8-3v-7"/></Icon>,
 cleaning:<Icon><path d="m12 3 1.1 3.4a5 5 0 0 0 3.2 3.2l3.4 1.1-3.4 1.1a5 5 0 0 0-3.2 3.2L12 18.5 10.9 15a5 5 0 0 0-3.2-3.2l-3.4-1.1 3.4-1.1a5 5 0 0 0 3.2-3.2L12 3Z"/></Icon>,
 standardization:<Icon><path d="M4 6h10M18 6h2M4 12h2M10 12h10M4 18h7M15 18h5"/><circle cx="16" cy="6" r="2"/><circle cx="8" cy="12" r="2"/><circle cx="13" cy="18" r="2"/></Icon>,
 merge:<Icon><path d="M5 4v4c0 2.2 1.8 4 4 4h6m0 0-3-3m3 3-3 3M5 20v-4c0-2.2 1.8-4 4-4"/></Icon>,
 validation:<Icon><path d="m5 12 4 4L19 6"/><circle cx="12" cy="12" r="9"/></Icon>,
 approval:<Icon><path d="M9 11l2 2 4-4"/><path d="M5 3h14v18H5z"/><path d="M9 17h6"/></Icon>,
 reports:<Icon><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></Icon>,
 audit:<Icon><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></Icon>,
 settings:<Icon><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1a8 8 0 0 0-1.8-1L14.4 3h-4.8l-.4 3.1a8 8 0 0 0-1.8 1l-2.4-1-2 3.4L5.1 11a7 7 0 0 0 0 2L3 14.5l2 3.4 2.4-1a8 8 0 0 0 1.8 1l.4 3.1h4.8l.4-3.1a8 8 0 0 0 1.8-1l2.4 1 2-3.4-2.1-1.5a7 7 0 0 0 .1-1Z"/></Icon>,
 rows:<Icon><path d="M4 6h16M4 12h16M4 18h16"/></Icon>, warning:<Icon><path d="m21.7 18-8-14a2 2 0 0 0-3.4 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.7-3Z"/><path d="M12 9v4M12 17h.01"/></Icon>,
 check:<Icon><circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16 9"/></Icon>, close:<Icon><circle cx="12" cy="12" r="9"/><path d="m9 9 6 6m0-6-6 6"/></Icon>,
 file:<Icon><path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v6h6"/></Icon>, download:<Icon><path d="M12 3v12m0 0 4-4m-4 4-4-4M5 21h14"/></Icon>,
 user:<Icon><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></Icon>, shield:<Icon><path d="M12 3 4 6v5c0 5 3.4 8.4 8 10 4.6-1.6 8-5 8-10V6l-8-3Z"/><path d="m9 12 2 2 4-4"/></Icon>, bell:<Icon><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></Icon>,
 arrow:<Icon><path d="M5 12h14m-5-5 5 5-5 5"/></Icon>, filter:<Icon><path d="M4 5h16M7 12h10M10 19h4"/></Icon>,
};

const nav=[
 ["Dashboard","dashboard","/"],["Upload Data","upload","/upload-data"],["Data Sources","database","/data-sources"],["Cleaning","cleaning","/cleaning"],["Standardization","standardization","/standardization"],["Match & Merge","merge","/match-merge"],["Validation","validation","/validation"],["Approval Queue","approval","/approval-queue"],["Reports","reports","/reports"],["Audit Log","audit","/audit-log"],["Settings","settings","/settings"]
] as const;
const titles:Record<OperationsPageKind,[string,string]>={
 cleaning:["Cleaning","Find and fix common data quality issues."],standardization:["Standardization","Make formats consistent across your data."],"match-merge":["Match & Merge","Review possible duplicates before combining records."],validation:["Validation","Check that your data is complete and ready to use."],"approval-queue":["Approval Queue","Review and approve changes suggested by AI."],reports:["Reports","View and download clear summaries of your data operations."],"audit-log":["Audit Log","See who changed what and when."],settings:["Settings","Manage your account and workspace preferences."]
};

function BrandLogo(){return <div className="brand-logo" aria-hidden="true"><svg viewBox="0 0 42 42" fill="none"><defs><linearGradient id="opsLogo" x1="8" y1="7" x2="35" y2="35"><stop stopColor="#C4B5FD"/><stop offset=".52" stopColor="#A855F7"/><stop offset="1" stopColor="#3B82F6"/></linearGradient></defs><path className="logo-links" stroke="url(#opsLogo)" d="m21 10-9 5.5v11L21 32l9-5.5v-11L21 10Zm0 0v8.5m-9-3 9 5 9-5m-9 5V32"/><path className="logo-core" stroke="url(#opsLogo)" d="m21 16.5 4 2.3v4.5l-4 2.2-4-2.2v-4.5l4-2.3Z"/><circle cx="21" cy="8" r="2.2"/><circle cx="10" cy="14.5" r="2.2"/><circle cx="32" cy="14.5" r="2.2"/><circle cx="10" cy="27.5" r="2.2"/><circle cx="32" cy="27.5" r="2.2"/><circle cx="21" cy="34" r="2.2"/></svg></div>}

function Shell({kind,children}: {kind:OperationsPageKind;children:ReactNode}){const [title,subtitle]=titles[kind];return <main className="dashboard-shell min-h-screen"><aside className="desktop-sidebar flex flex-col border-r border-slate-800/70 bg-[#070a16]/90 p-3 backdrop-blur-xl"><Link href="/" className="flex items-center gap-3 rounded-xl px-2 py-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#A855F7]"><BrandLogo/><div><div className="font-semibold tracking-tight">AI Data</div><div className="text-xs text-slate-400">Operations</div></div></Link><nav className="mt-5 space-y-1" aria-label="Main navigation">{nav.map(([label,icon,href])=><Link key={label} href={href} className={`nav-item ${href===`/${kind}`?"upload-nav-active":""}`} aria-current={href===`/${kind}`?"page":undefined}><span className="h-[18px] w-[18px]">{icons[icon]}</span><span>{label}</span>{label==="Approval Queue"&&<span className="ml-auto rounded-full bg-[#8B5CF6]/20 px-2 py-0.5 text-[11px] text-[#C4B5FD]">2</span>}</Link>)}</nav><div className="mt-auto rounded-xl border border-slate-800/80 bg-white/[.025] p-3"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#211A45] text-sm font-medium text-[#C4B5FD]">S</div><div><div className="text-sm font-medium">Salman</div><div className="text-xs text-slate-500">Admin</div></div></div></div></aside><div className="dashboard-content overflow-hidden px-5 py-7 sm:px-7 lg:px-9 lg:py-9"><header><h1 className="text-3xl font-semibold tracking-[-0.035em]">{title}</h1><p className="mt-2 text-sm text-slate-400 sm:text-base">{subtitle}</p></header>{children}</div></main>}

type Metric={label:string,value:string,note:string,tone:string,icon:keyof typeof icons};
function Summary({items}:{items:Metric[]}){return <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Summary">{items.map(item=><article className="ops-summary card p-4" key={item.label}><div className="flex items-center justify-between"><span className="text-sm text-slate-400">{item.label}</span><span className="ops-summary-icon" style={{color:item.tone,backgroundColor:`${item.tone}10`,borderColor:`${item.tone}25`}}>{icons[item.icon]}</span></div><p className="mt-4 text-3xl font-semibold tracking-[-.035em]">{item.value}</p><p className="mt-2 text-xs text-slate-500">{item.note}</p></article>)}</section>}
function Badge({children,tone="#22C55E"}:{children:ReactNode;tone?:string}){return <span className="whitespace-nowrap rounded-full px-2.5 py-1 text-xs font-medium" style={{color:tone,backgroundColor:`${tone}12`}}>{children}</span>}
function Action({children,tone="purple"}:{children:ReactNode;tone?:"purple"|"green"|"red"}){return <button type="button" className={`ops-action ops-action-${tone}`}>{children}</button>}
function SectionTitle({title,subtitle}:{title:string;subtitle?:string}){return <div><h2 className="font-semibold">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-slate-500">{subtitle}</p>}</div>}
function StateNote({kind,text}:{kind:"loading"|"empty"|"success"|"error";text:string}){const tone={loading:"#3B82F6",empty:"#94A3B8",success:"#22C55E",error:"#EF4444"}[kind];return <div className="state-note" style={{color:tone,borderColor:`${tone}22`,backgroundColor:`${tone}08`}}><span className="h-4 w-4">{kind==="success"?icons.check:kind==="error"?icons.close:kind==="loading"?icons.audit:icons.file}</span><span>{text}</span></div>}

const commonJobs=[{file:"Customer_Data.csv",time:"Today, 9:42 AM",status:"Complete",tone:"#22C55E"},{file:"Sales_Records.xlsx",time:"Yesterday, 3:18 PM",status:"Needs Review",tone:"#F59E0B"},{file:"Inventory_List.csv",time:"Jul 30, 11:05 AM",status:"Complete",tone:"#22C55E"}];
function Jobs({title="Recent Jobs"}:{title?:string}){return <section className="card mt-5 p-5 sm:p-6"><SectionTitle title={title} subtitle="Latest activity from your uploaded files"/><div className="mt-4 divide-y divide-slate-800/80">{commonJobs.map(job=><div key={job.file} className="flex items-center gap-3 py-4"><span className="list-icon text-[#A855F7]">{icons.file}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{job.file}</p><p className="mt-1 text-xs text-slate-500">{job.time}</p></div><Badge tone={job.tone}>{job.status}</Badge><Action>View details</Action></div>)}</div></section>}
function Comparison({title="Before & After",before,after}:{title?:string;before:string;after:string}){return <section className="card p-5 sm:p-6"><SectionTitle title={title} subtitle="A clear preview of the suggested change"/><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="comparison-box"><span>Before</span><p>{before}</p></div><div className="comparison-box comparison-after"><span>After</span><p>{after}</p></div></div></section>}

function Cleaning(){return <><Summary items={[{label:"Rows scanned",value:"12,480",note:"Across 3 files",tone:"#3B82F6",icon:"rows"},{label:"Issues found",value:"186",note:"Duplicates and missing values",tone:"#F59E0B",icon:"warning"},{label:"Fixes applied",value:"164",note:"Safe fixes completed",tone:"#22C55E",icon:"check"},{label:"Needs review",value:"22",note:"Waiting for your decision",tone:"#A855F7",icon:"approval"}]}/><div className="mt-5 grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Comparison before="(312) 555-0198" after="+1 312 555 0198"/><section className="card p-5 sm:p-6"><SectionTitle title="Current Status" subtitle="Customer_Data.csv"/><div className="mt-4 flex flex-wrap items-center gap-3"><Badge>164 fixes applied</Badge><Badge tone="#F59E0B">22 need review</Badge><Action>View details</Action></div></section></div><Jobs title="Recent Cleaning Jobs"/></>}
function Standardization(){return <><Summary items={[{label:"Fields standardized",value:"48",note:"Names, dates, and addresses",tone:"#3B82F6",icon:"standardization"},{label:"Formats corrected",value:"324",note:"Values made consistent",tone:"#22C55E",icon:"check"},{label:"Records updated",value:"2,840",note:"Across recent jobs",tone:"#A855F7",icon:"rows"},{label:"Needs review",value:"12",note:"Unclear formats",tone:"#F59E0B",icon:"warning"}]}/><div className="mt-5 grid gap-5 md:grid-cols-2"><Comparison title="Phone format" before="312.555.0198" after="+1 312 555 0198"/><Comparison title="Date format" before="8/1/26" after="2026-08-01"/></div><Jobs title="Recent Standardization Jobs"/></>}
function MatchMerge(){const matches=[{a:"Acme Incorporated",b:"ACME Inc.",score:"96%"},{a:"Northwind Trading",b:"Northwind Traders",score:"91%"}];return <><Summary items={[{label:"Possible duplicates",value:"24",note:"Ready to review",tone:"#F59E0B",icon:"warning"},{label:"Matches found",value:"18",note:"High-confidence suggestions",tone:"#3B82F6",icon:"merge"},{label:"Merged records",value:"142",note:"Previously approved",tone:"#22C55E",icon:"check"},{label:"Needs approval",value:"6",note:"No changes made yet",tone:"#A855F7",icon:"approval"}]}/><section className="mt-5"><SectionTitle title="Suggested Matches" subtitle="Review each suggestion before any records are combined"/><div className="mt-4 grid gap-4 lg:grid-cols-2">{matches.map(match=><article className="card p-5" key={match.a}><div className="flex items-start justify-between gap-3"><Badge tone="#3B82F6">{match.score} confidence</Badge><span className="h-5 w-5 text-[#A78BFA]">{icons.merge}</span></div><div className="mt-4 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="comparison-box"><span>Record A</span><p>{match.a}</p></div><span className="text-slate-600">+</span><div className="comparison-box"><span>Record B</span><p>{match.b}</p></div></div><div className="mt-4 flex gap-2"><Action tone="green">Approve</Action><Action tone="red">Reject</Action></div></article>)}</div></section><StateNote kind="empty" text="No records are merged until you approve a suggestion."/></>}
function Validation(){const rows=[{record:"Customer #1042",check:"Email address",result:"Passed",tone:"#22C55E",recommendation:"No action needed"},{record:"Customer #1088",check:"Phone number",result:"Warning",tone:"#F59E0B",recommendation:"Confirm the country code"},{record:"Order #8821",check:"Required fields",result:"Failed",tone:"#EF4444",recommendation:"Add a shipping address"}];return <><Summary items={[{label:"Records checked",value:"8,240",note:"Latest validation run",tone:"#3B82F6",icon:"rows"},{label:"Passed",value:"7,986",note:"Ready to use",tone:"#22C55E",icon:"check"},{label:"Warnings",value:"218",note:"Worth checking",tone:"#F59E0B",icon:"warning"},{label:"Failed",value:"36",note:"Action required",tone:"#EF4444",icon:"close"}]}/><section className="card mt-5 p-5 sm:p-6"><SectionTitle title="Validation Results" subtitle="Issues are shown with a clear next step"/><ResponsiveTable headers={["Record","Check","Severity","Recommendation","Action"]} rows={rows.map(row=>[row.record,row.check,<Badge key="badge" tone={row.tone}>{row.result}</Badge>,row.recommendation,<Action key="action">View details</Action>])}/></section></>}
function ApprovalQueue(){return <><Summary items={[{label:"Waiting",value:"22",note:"Items in the queue",tone:"#A855F7",icon:"approval"},{label:"High priority",value:"4",note:"Review these first",tone:"#EF4444",icon:"warning"},{label:"Approved today",value:"18",note:"Changes accepted",tone:"#22C55E",icon:"check"},{label:"Rejected today",value:"3",note:"Suggestions declined",tone:"#94A3B8",icon:"close"}]}/><section className="card mt-5 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><SectionTitle title="Duplicate customer record" subtitle="Customer_Data.csv · High priority"/><Badge tone="#3B82F6">94% confidence</Badge></div><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_.75fr]"><Comparison title="Suggested change" before="Acme Incorporated" after="ACME Inc."/><div className="rounded-xl border border-slate-800/80 bg-white/[.015] p-4"><p className="text-sm font-medium">Why AI recommends this</p><p className="mt-2 text-sm leading-6 text-slate-400">The company name, phone number, and street address match. Keeping one record can prevent duplicate outreach.</p><div className="mt-5 flex gap-2"><Action tone="green">Approve</Action><Action tone="red">Reject</Action></div></div></div></section><StateNote kind="success" text="Approved and rejected actions are dummy previews only."/></>}
function Reports(){const reports=[{name:"Weekly Data Health",date:"Aug 1, 2026",type:"PDF"},{name:"Cleaning Summary",date:"Jul 31, 2026",type:"CSV"},{name:"Validation Results",date:"Jul 30, 2026",type:"PDF"}];return <><Summary items={[{label:"Latest health score",value:"96%",note:"Up 4% this week",tone:"#22C55E",icon:"check"},{label:"Completed jobs",value:"18",note:"In the last 30 days",tone:"#3B82F6",icon:"rows"},{label:"Issues resolved",value:"624",note:"Across all operations",tone:"#A855F7",icon:"cleaning"},{label:"Reports generated",value:"12",note:"Ready to view",tone:"#F59E0B",icon:"reports"}]}/><section className="card mt-5 p-5 sm:p-6"><SectionTitle title="Recent Reports" subtitle="View or download your latest summaries"/><div className="mt-4 divide-y divide-slate-800/80">{reports.map(report=><div className="report-row" key={report.name}><span className="list-icon text-[#A855F7]">{icons.file}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{report.name}</p><p className="mt-1 text-xs text-slate-500">{report.date} · {report.type}</p></div><div className="flex flex-wrap gap-2"><Action>View</Action><Action><span className="inline-flex items-center gap-1"><span className="h-3.5 w-3.5">{icons.download}</span>Download {report.type}</span></Action><Action><span className="hidden xl:inline">Download Clean Data</span><span className="xl:hidden">Clean Data</span></Action></div></div>)}</div></section><StateNote kind="loading" text="Download buttons show frontend-only placeholder states."/></>}
function ResponsiveTable({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <div className="responsive-table mt-4 overflow-x-auto"><table className="w-full border-collapse text-left text-sm"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j} data-label={headers[j]}>{cell}</td>)}</tr>)}</tbody></table></div>}
function AuditLog(){const rows=[["Aug 1, 9:42 AM","Salman","Approved cleanup","Customer_Data.csv",<Badge key="1">Success</Badge>],["Aug 1, 9:18 AM","System","Completed validation","Sales_Records.xlsx",<Badge key="2">Success</Badge>],["Jul 31, 4:06 PM","Salman","Rejected match","Customer #1088",<Badge key="3" tone="#94A3B8">Declined</Badge>]];return <><section className="card mt-7 p-5 sm:p-6"><div className="flex items-center gap-2"><span className="h-5 w-5 text-[#A78BFA]">{icons.filter}</span><SectionTitle title="Filters" subtitle="Narrow the activity shown below"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Filter label="Date" options={["Last 7 days","Last 30 days"]}/><Filter label="User" options={["All users","Salman","System"]}/><Filter label="Action" options={["All actions","Approval","Validation","Cleaning"]}/><Filter label="Status" options={["All statuses","Success","Declined","Failed"]}/></div></section><section className="card mt-5 p-5 sm:p-6"><SectionTitle title="Activity" subtitle="A readable record of recent workspace changes"/><ResponsiveTable headers={["Timestamp","Actor","Action","Item","Result"]} rows={rows}/></section><StateNote kind="empty" text="If filters return no activity, an empty-state message will appear here."/></>}
function Filter({label,options}:{label:string;options:string[]}){return <label className="text-xs font-medium text-slate-400">{label}<select className="ops-input mt-2"><>{options.map(o=><option key={o}>{o}</option>)}</></select></label>}

function Settings(){const [saved,setSaved]=useState("");const save=(name:string)=>{setSaved(`${name} saved`);window.setTimeout(()=>setSaved(""),2200)};return <><div aria-live="polite" className="mt-5 min-h-9">{saved&&<StateNote kind="success" text={saved}/>}</div><div className="grid gap-5 xl:grid-cols-2"><SettingsSection title="Profile" icon="user" onSave={()=>save("Profile")}><Field label="Full name" value="Salman"/><Field label="Email" value="salman@example.com" type="email"/></SettingsSection><SettingsSection title="Organization" icon="database" onSave={()=>save("Organization")}><Field label="Organization name" value="AI Data Operations"/><Field label="Time zone" value="America/Chicago"/></SettingsSection><SettingsSection title="Users" icon="user" onSave={()=>save("Users")}><Field label="Default role" value="Member"/><p className="text-xs text-slate-500">3 active users in this workspace.</p></SettingsSection><section className="card p-5 sm:p-6"><div className="flex items-center gap-2"><span className="h-5 w-5 text-[#A78BFA]">{icons.shield}</span><h2 className="font-semibold">Two-factor authentication</h2></div><div className="mt-5"><TwoFactorSettings/></div></section><SettingsSection title="Notifications" icon="bell" onSave={()=>save("Notifications")}><label className="setting-toggle"><input type="checkbox" defaultChecked/><span>Job completion emails</span></label><label className="setting-toggle"><input type="checkbox" defaultChecked/><span>Approval reminders</span></label></SettingsSection><SettingsSection title="Data Retention" icon="audit" onSave={()=>save("Retention settings")} danger><Field label="Keep activity history" value="90 days"/><p className="text-xs leading-5 text-slate-500">Shorter retention removes older history. This demo does not delete data.</p></SettingsSection></div><StateNote kind="error" text="Form errors will appear here if a value cannot be saved."/></>}
function Field({label,value,type="text"}:{label:string;value:string;type?:string}){return <label className="text-xs font-medium text-slate-400">{label}<input className="ops-input mt-2" type={type} defaultValue={value}/></label>}
function SettingsSection({title,icon,onSave,danger,children}:{title:string;icon:keyof typeof icons;onSave:()=>void;danger?:boolean;children:ReactNode}){return <section className={`card p-5 sm:p-6 ${danger?"danger-settings":""}`}><div className="flex items-center gap-2"><span className={`h-5 w-5 ${danger?"text-[#EF4444]":"text-[#A78BFA]"}`}>{icons[icon]}</span><h2 className="font-semibold">{title}</h2></div><div className="mt-5 grid gap-4">{children}</div><button type="button" className={`ops-action mt-5 ${danger?"ops-action-red":"ops-action-purple"}`} onClick={onSave}>Save changes</button></section>}

export default function OperationsPage({kind}:{kind:OperationsPageKind}){return <Shell kind={kind}>{kind==="cleaning"?<Cleaning/>:kind==="standardization"?<Standardization/>:kind==="match-merge"?<MatchMerge/>:kind==="validation"?<Validation/>:kind==="approval-queue"?<ApprovalQueue/>:kind==="reports"?<Reports/>:kind==="audit-log"?<AuditLog/>:<Settings/>}</Shell>}
