"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export default function SignupPage() {
  const router = useRouter(); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const data=new FormData(event.currentTarget);if(data.get("password")!==data.get("confirm_password")){setError("Passwords do not match.");return}setLoading(true);try{const response=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({full_name:data.get("full_name"),organization_name:data.get("organization_name"),email:data.get("email"),password:data.get("password")})});const payload=await response.json().catch(()=>null);if(!response.ok){setError(typeof payload?.detail==="string"?payload.detail:"Unable to create your account.");return}router.replace("/2fa/setup");router.refresh()}catch{setError("Unable to reach the authentication service.")}finally{setLoading(false)}}
  return <main className="login-shell"><section className="login-card signup-card card"><div className="login-mark" aria-hidden="true">AI</div><p className="login-eyebrow">AI Data Operations</p><h1>Create your workspace</h1><p className="login-copy">Your first account is the organization administrator and requires authenticator-app security.</p><form className="login-form" onSubmit={submit}><label>Full Name<input className="ops-input" name="full_name" autoComplete="name" required disabled={loading}/></label><label>Company Name<input className="ops-input" name="organization_name" autoComplete="organization" required disabled={loading}/></label><label>Email<input className="ops-input" name="email" type="email" autoComplete="email" required disabled={loading}/></label><label>Password<input className="ops-input" name="password" type="password" minLength={8} autoComplete="new-password" required disabled={loading}/></label><label>Confirm Password<input className="ops-input" name="confirm_password" type="password" minLength={8} autoComplete="new-password" required disabled={loading}/></label><label className="terms-check"><input name="terms" type="checkbox" required disabled={loading}/><span>I agree to the Terms of Service and Privacy Policy.</span></label>{error&&<div className="login-error" role="alert">{error}</div>}<button className="glow-button login-submit" type="submit" disabled={loading}>{loading?"Creating account…":"Create account"}</button></form><p className="auth-switch">Already have an account? <Link href="/login">Sign in</Link></p></section></main>;
}
