"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import RecoveryCodes from "../../components/RecoveryCodes";

type Setup={secret:string;provisioning_uri:string};
export default function TwoFactorSetupPage(){const router=useRouter();const [setup,setSetup]=useState<Setup|null>(null);const [codes,setCodes]=useState<string[]|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
  useEffect(()=>{fetch("/api/auth/2fa/setup",{method:"POST"}).then(async response=>{const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.detail??"Unable to start setup.");setSetup(body)}).catch(error=>setError(error.message)).finally(()=>setLoading(false))},[]);
  async function verify(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setLoading(true);const code=new FormData(event.currentTarget).get("code");try{const response=await fetch("/api/auth/2fa/setup/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code})});const body=await response.json().catch(()=>null);if(!response.ok){setError(body?.detail??"Verification failed.");return}setCodes(body.recovery_codes)}catch{setError("Unable to reach the authentication service.")}finally{setLoading(false)}}
  return <main className="login-shell"><section className="login-card setup-card card"><div className="login-mark" aria-hidden="true">2FA</div><p className="login-eyebrow">Authenticator security</p><h1>Protect your account</h1>{codes?<RecoveryCodes codes={codes} onContinue={()=>{router.replace("/");router.refresh()}}/>:<>{loading&&!setup&&<div className="auth-loading"><span className="login-spinner"/>Preparing secure setup…</div>}{setup&&<><ol className="setup-steps"><li>Open your authenticator app and add an account manually.</li><li>Enter this setup key, or import the provisioning URI.</li></ol><div className="secret-box"><span>Setup key</span><code>{setup.secret}</code></div><details className="provisioning-uri"><summary>Show provisioning URI</summary><code>{setup.provisioning_uri}</code></details><form className="login-form" onSubmit={verify}><label>6-digit authentication code<input className="ops-input code-input" name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required disabled={loading}/></label>{error&&<div className="login-error" role="alert">{error}</div>}<button className="glow-button login-submit" disabled={loading}>{loading?"Verifying…":"Verify and enable"}</button></form></>}{error&&!setup&&<div className="login-error" role="alert">{error}</div>}</>}</section></main>}
